[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    'ds-test/=lib/ds-test/src/',
    'chainlink/=lib/chainlink-brownie-contracts/contracts/src/v0.8/'
    ]
verbosity = 3

# See more config options https://github.com/gakonst/foundry/tree/master/config